# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:12.10
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Asia/Tokyo"
    ports:
      - 15432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data