/*
 * サンプルAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package presentation

import (
	"context"
	"net/http"
)

// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface {
	AdminGetTweetFavoriteList(http.ResponseWriter, *http.Request)
	DeleteFavorite(http.ResponseWriter, *http.Request)
	GetFavorite(http.ResponseWriter, *http.Request)
	PostFavorite(http.ResponseWriter, *http.Request)
}

// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface {
	AdminGetTweetFavoriteList(context.Context) (ImplResponse, error)
	DeleteFavorite(context.Context, int32) (ImplResponse, error)
	GetFavorite(context.Context) (ImplResponse, error)
	PostFavorite(context.Context, TweetId) (ImplResponse, error)
}
