/*
 * サンプルAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package presentation

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service      DefaultApiServicer
	errorHandler ErrorHandler
}

// DefaultApiOption for how the controller is set up.
type DefaultApiOption func(*DefaultApiController)

// WithDefaultApiErrorHandler inject ErrorHandler into controller
func WithDefaultApiErrorHandler(h ErrorHandler) DefaultApiOption {
	return func(c *DefaultApiController) {
		c.errorHandler = h
	}
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer, opts ...DefaultApiOption) Router {
	controller := &DefaultApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{
		{
			"AdminGetTweetFavoriteList",
			strings.ToUpper("Get"),
			"/tweet/favorite",
			c.AdminGetTweetFavoriteList,
		},
		{
			"DeleteFavorite",
			strings.ToUpper("Delete"),
			"/users/my/favorite/{tweetId}",
			c.DeleteFavorite,
		},
		{
			"GetFavorite",
			strings.ToUpper("Get"),
			"/users/my/favorite",
			c.GetFavorite,
		},
		{
			"PostFavorite",
			strings.ToUpper("Post"),
			"/users/my/favorite",
			c.PostFavorite,
		},
	}
}

// AdminGetTweetFavoriteList - ツイートごとのお気に入り数を取得
func (c *DefaultApiController) AdminGetTweetFavoriteList(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.AdminGetTweetFavoriteList(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// DeleteFavorite - ツイート店舗をお気に入りから削除
func (c *DefaultApiController) DeleteFavorite(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	tweetIdParam, err := parseInt32Parameter(params["tweetId"], true)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}

	result, err := c.service.DeleteFavorite(r.Context(), tweetIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// GetFavorite - お気に入りに登録したツイートIDを取得
func (c *DefaultApiController) GetFavorite(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetFavorite(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// PostFavorite - ツイート店舗をお気に入りに登録
func (c *DefaultApiController) PostFavorite(w http.ResponseWriter, r *http.Request) {
	tweetIdParam := TweetId{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&tweetIdParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertTweetIdRequired(tweetIdParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.PostFavorite(r.Context(), tweetIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
