/*
 * サンプルAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package presentation

type TweetFavoriteList struct {
	Results []TweetFavorite `json:"results,omitempty"`
}

// AssertTweetFavoriteListRequired checks if the required fields are not zero-ed
func AssertTweetFavoriteListRequired(obj TweetFavoriteList) error {
	for _, el := range obj.Results {
		if err := AssertTweetFavoriteRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseTweetFavoriteListRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TweetFavoriteList (e.g. [][]TweetFavoriteList), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTweetFavoriteListRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTweetFavoriteList, ok := obj.(TweetFavoriteList)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTweetFavoriteListRequired(aTweetFavoriteList)
	})
}
