/*
 * サンプルAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package presentation

import (
	"time"
)

type Favorite struct {

	// ツイートID
	TweetId string `json:"tweet_id,omitempty"`

	// お気に入りに登録した日時
	RegisteredAt time.Time `json:"registered_at,omitempty"`
}

// AssertFavoriteRequired checks if the required fields are not zero-ed
func AssertFavoriteRequired(obj Favorite) error {
	return nil
}

// AssertRecurseFavoriteRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Favorite (e.g. [][]Favorite), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFavoriteRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFavorite, ok := obj.(Favorite)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFavoriteRequired(aFavorite)
	})
}
