/*
 * サンプルAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package presentation

type TweetFavorite struct {
	TweetId string `json:"tweet_id,omitempty"`

	Favorite int64 `json:"favorite,omitempty"`
}

// AssertTweetFavoriteRequired checks if the required fields are not zero-ed
func AssertTweetFavoriteRequired(obj TweetFavorite) error {
	return nil
}

// AssertRecurseTweetFavoriteRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TweetFavorite (e.g. [][]TweetFavorite), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTweetFavoriteRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTweetFavorite, ok := obj.(TweetFavorite)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTweetFavoriteRequired(aTweetFavorite)
	})
}
