/*
 * サンプルAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package presentation

type TweetId struct {
	TweetId string `json:"tweetId,omitempty"`
}

// AssertTweetIdRequired checks if the required fields are not zero-ed
func AssertTweetIdRequired(obj TweetId) error {
	return nil
}

// AssertRecurseTweetIdRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TweetId (e.g. [][]TweetId), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTweetIdRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTweetId, ok := obj.(TweetId)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTweetIdRequired(aTweetId)
	})
}
