/*
 * サンプルAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package presentation

type FavoriteList struct {
	Results []Favorite `json:"results,omitempty"`
}

// AssertFavoriteListRequired checks if the required fields are not zero-ed
func AssertFavoriteListRequired(obj FavoriteList) error {
	for _, el := range obj.Results {
		if err := AssertFavoriteRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseFavoriteListRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FavoriteList (e.g. [][]FavoriteList), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFavoriteListRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFavoriteList, ok := obj.(FavoriteList)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFavoriteListRequired(aFavoriteList)
	})
}
