/*
 * サンプルAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"github.com/empenguin1186/go-api-sample/infra"
	"github.com/empenguin1186/go-api-sample/presentation"
	"log"
	"net/http"
	"os"
)

func main() {
	log.Printf("Server started")

	db, tx, err := infra.NewPostgre()
	if err != nil {
		fmt.Printf("database error occurred. %v", err)
		os.Exit(1)
	}

	dataSource := infra.NewDataSource(db, tx)
	favoriteRepository := infra.NewFavoriteRepositoryImpl(dataSource)

	DefaultApiService := presentation.NewDefaultApiService(favoriteRepository)
	DefaultApiController := presentation.NewDefaultApiController(DefaultApiService)

	router := presentation.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
