/*
 * サンプルAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/empenguin1186/go-api-sample/presentation"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := presentation.NewDefaultApiService()
	DefaultApiController := presentation.NewDefaultApiController(DefaultApiService)

	router := presentation.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
